name: Sphinx

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install LaTex and packages
        run: |
          sudo apt install latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-lang-greek tex-gyre
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run make
        run: |
          ls -l
          tree
          make html
          make latexpdf
