name: AIRR Terminology compile and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sphinx:
    name: Run Sphinx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install LaTex and packages
        run: |
          sudo apt install latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-lang-greek tex-gyre
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run make
        run: |
          make html
          make latexpdf
      - name: Upload compiled PDF
        uses: actions/upload-artifact@v3
        with:
          name: document-compiled-pdf
          path: _build/latex/airrcommunityterminology.pdf
  zenodo:
    name: Upload to Zenodo
    needs: sphinx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download compiled PDF
        uses: actions/download-artifact@v3
        with:
          name: document-compiled-pdf
      - name: Deploy on Zenodo
        env:
          ZENODO_TOKEN: ${{ secrets.ZENODO_SANDBOX_BUSSEC }}
        run: |
          python zenodo_upload.py

